version: '2'
services:
  google:
    image: flaccid/sitemap-crawler
    stdin_open: true
    tty: true
    command:
    - -d
    - -a
    - -t
    - '64'
    - https://www.google.com/sitemap.xml
    labels:
      io.rancher.container.pull_image: always
