version: '2'
services:
  google:
    image: aleravat/crowlet
    stdin_open: true
    tty: true
    command:
    - --debug
    - -t
    - '64'
    - https://www.google.com/sitemap.xml
    labels:
      io.rancher.container.pull_image: always
